version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages
      prefix: "fix(deps): "
