name: Composer CI

on:
  workflow_call:
    inputs:
      db_schema:
        required: true
        type: string
      db_archive_schema:
        required: false
        type: string
        default: db_archive
      php_version:
        required: true
        type: string
        default: "8.4"
      php_extensions:
        type: string
        required: false
        default: gd zip mcrypt pdo_pgsql
      install_auth:
        type: boolean
        required: false
        default: false
      use_database:
        type: boolean
        required: false
        default: true
      run_migrations:
        type: boolean
        required: false
        default: true
    secrets:
      COMPOSER_AUTH_REPO:
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    services:
      psql:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: testing123
          POSTGRES_DB: jenkins_test
        ports:
          - 5432
    steps:
      - uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path:  ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              ${{ runner.os }}-composer-

      # - name: Add HTTP basic auth credentials
      #   run: echo '${{ secrets.COMPOSER_AUTH_REPO }}' > $GITHUB_WORKSPACE/auth.json

      - uses: shivammathur/setup-php@v2
        with:
          tools: composer
          php-version: ${{inputs.php_version}}
          extensions: ${{inputs.php_extensions}}
        env:
          CI: true
          GITHUB_TOKEN: ${{secrets.COMPOSER_AUTH_REPO}}
      - name: Install Dependencies
        shell: bash
        run: composer install --no-progress --no-suggest --no-interaction

      - name: Set ENV
        run: cp .env.ci .env

      - name: Create Schema
        if: ${{inputs.use_database}}
        run: psql --host 127.0.0.1 --port ${{ job.services.psql.ports['5432'] }} -U postgres -d jenkins_test  -c "CREATE SCHEMA ${{inputs.db_schema}}; GRANT usage on schema ${{inputs.db_schema}} to postgres; grant create on schema ${{inputs.db_schema}} to postgres;"
        env:
          PGPASSWORD: testing123

      - name: Create Archive DB
        if: ${{inputs.use_database}}
        run: psql --host 127.0.0.1 --port ${{ job.services.psql.ports['5432'] }} -U postgres -d jenkins_test  -c "CREATE SCHEMA  ${{inputs.db_archive_schema}}; GRANT usage on schema  ${{inputs.db_archive_schema}} to postgres; grant create on schema ${{inputs.db_archive_schema}} to postgres;"
        env:
          PGPASSWORD: testing123

      - name: Verify Postgres connection from host
        if: ${{inputs.use_database}}
        run: psql --host 127.0.0.1 --port ${{ job.services.psql.ports['5432'] }} -U postgres  -d jenkins_test -c "SET search_path TO ${{inputs.db_schema}}"
        env:
          PGPASSWORD: testing123

      - name: Migrate
        if: ${{inputs.run_migrations}}
        shell: bash
        run: php artisan migrate --force
        env:
          CI: true
          DB_PORT: ${{ job.services.psql.ports['5432'] }}
          DB_PASSWORD: testing123
          DB_SCHEMA: "${{inputs.db_schema}}"
          DB_CONNECTION: "pgsql"
          DB_USERNAME: postgres

      - name: Install Auth
        if: ${{inputs.install_auth}}

        shell: bash
        run: php artisan passport:install
        env:
          CI: true
          DB_PORT: ${{ job.services.psql.ports['5432'] }}
          DB_PASSWORD: testing123
          DB_SCHEMA: "${{inputs.db_schema}}"
          DB_CONNECTION: "pgsql"
          DB_USERNAME: postgres
      - name: Test
        shell: bash
        run: ./vendor/bin/phpunit
        env:
          CI: true
          DB_PORT: ${{ job.services.psql.ports['5432'] }}
          DB_PASSWORD: testing123
          DB_SCHEMA: "${{inputs.db_schema}}"
          DB_CONNECTION: "pgsql"
          DB_USERNAME: postgres
