name: Deploy Service

on:
  workflow_call:
    inputs:
      gh_environment:
        required: true
        type: string
      commit_hash:
        required: true
        type: string
      service:
        required: true
        type: string
jobs:
  deploy:
    name: Deploy to ${{ inputs.service }}${{ inputs.gh_environment }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.gh_environment }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.commit_hash }}
          show-progress: false
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ vars.GCP_SA_EMAIL }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          create_credentials_file: true
          token_format: access_token
          project_id: ${{ vars.GCP_PROJECT_ID }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          install_components: kubectl,gke-gcloud-auth-plugin,kustomize,skaffold
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ vars.K8S_CLUSTER_NAME }}
          location: ${{ vars.K8S_CLUSTER_LOCATION }}
          use_auth_provider: true
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: 'True'
      - name: 'Get GKE Credentials'
        shell: bash
        run: |
          gcloud container clusters get-credentials ${{ vars.K8S_CLUSTER_NAME }} --zone ${{ vars.K8S_CLUSTER_LOCATION }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: 'True'
      - name: Deploy to environment
        shell: bash
        run: |
          echo "Deploying to environment ${{ inputs.gh_environment }}"
          cd deployments
          skaffold deploy -p ${{ inputs.gh_environment }} --images gcr.io/cybrary-204817/${{ inputs.service }}:${{ inputs.commit_hash }} --default-repo gcr.io/cybrary-204817
